### PR TITLE
Change package to io.diffblue.javademo

### PR DESCRIPTION
**Pull request by allredj**
fuzztest does not like the `com.diffblue` prefix.

### CODE REVIEW

**Comment by allredj** [comment]
If this change goes through, user documentation will have to be updated.

**Review by jeannielynnmoulton — COMMENTED** [review]
Seems like a good idea to me, but I think some tests and maybe some CIs will have to be updated on cover-ui and maybe elsewhere? @yumibagge

**Review by JimmehAH — APPROVED** [review]

**Review by paulkennethkent — APPROVED** [review]

**Comment by rjmunro** [comment]
Wasn't the problem that required this fixed?

**Comment by allredj** [comment]
I don't think so. @cesaro?

**Comment by peterschrammel** [comment]
It hasn't been fixed yet. It creates tests with assertions for return values, but not for side effects afaik.

**Pull request merged**
